cluster:
  name:                         {{ app_name }}

path:
  home:                         /usr/share/elasticsearch
  conf:                         {{ elastic_conf }}
  logs:                         {{ log_dir }}
  data:                         {{ elastic_data }}

node:
  name:                         ${HOSTNAME}
  data:                         true
