---

# Base packages
- name: Install pip
  apt: name=python-pip state=present
  tags:
    - base
    - provision

- name: Make sure pip upgraded
  command: easy_install -U pip
  tags:
      - base
      - provision

- name: Make sure curl in installed
  apt: name=curl state=present
  tags:
      - base
      - provision